"""
_ci_utils.py — code_improver 파일 처리 유틸리티 및 Python 복잡도 계산.

포함 요소:
- 파일 읽기 / 스킵 판단 (read_file_safe, is_binary, is_minified, ...)
- 소스 조각 추출 (extract_snippet)
- 보안 패턴 헬퍼 (_find_embedded_credential_url, _in_comment_or_string)
- Python AST 복잡도 계산 (_ComplexityVisitor, _python_cyclomatic, _first_code_line)
"""

from __future__ import annotations

import ast
import os
from pathlib import Path
from typing import List, Optional, Tuple
from urllib.parse import urlsplit

from execution._ci_models import (
    HASHED_BUNDLE_PATTERN,
    URL_CANDIDATE_PATTERN,
)


# ---------------------------------------------------------------------------
# File helpers
# ---------------------------------------------------------------------------


# [FIX #1] Added OSError handling for permission denied / locked files
def read_file_safe(file_path: str) -> Optional[str]:
    for enc in ("utf-8", "latin-1"):
        try:
            return Path(file_path).read_text(encoding=enc)
        except (UnicodeDecodeError, ValueError):
            continue
        except OSError:
            return None
    return None


def is_binary(file_path: str) -> bool:
    try:
        with open(file_path, "rb") as f:
            chunk = f.read(8192)
        return b"\x00" in chunk
    except OSError:
        return True


def is_minified(source: str) -> bool:
    lines = source.split("\n")
    if len(lines) < 3:
        return any(len(ln) > 5000 for ln in lines)
    avg_len = sum(len(ln) for ln in lines) / max(len(lines), 1)
    return avg_len > 500


def is_generated(source: str) -> bool:
    header = source[:1000].lower()
    markers = [
        "generated by",
        "auto-generated",
        "@generated",
        "do not edit",
        "automatically generated",
        "this file is generated",
    ]
    return any(m in header for m in markers)


def is_generated_filename(file_path: str) -> bool:
    name = Path(file_path).name
    if name.lower().startswith("workbox-"):
        return True
    return bool(HASHED_BUNDLE_PATTERN.match(name))


def should_skip(file_path: str, source: str, max_size: int) -> Tuple[bool, str]:
    try:
        size = os.path.getsize(file_path)
    except OSError:
        return True, "Cannot access file"
    if size > max_size:
        return True, f"File too large ({size} bytes > {max_size})"
    if is_binary(file_path):
        return True, "Binary file"
    if not source or not source.strip():
        return True, "Empty file"
    if is_minified(source):
        return True, "Minified file"
    if is_generated(source):
        return True, "Generated file"
    if is_generated_filename(file_path):
        return True, "Generated bundle file"
    return False, ""


def extract_snippet(lines: List[str], line_num: int, context: int = 0) -> str:
    idx = line_num - 1
    start = max(0, idx - context)
    end = min(len(lines), idx + context + 1)
    return "\n".join(lines[start:end]).rstrip()


# ---------------------------------------------------------------------------
# Security pattern helpers
# ---------------------------------------------------------------------------


def _find_embedded_credential_url(line: str) -> Optional[str]:
    """Return a URL with userinfo (username/password) embedded in the authority if found."""
    for match in URL_CANDIDATE_PATTERN.finditer(line):
        candidate = match.group(0).rstrip(".,);]")
        try:
            parsed = urlsplit(candidate)
        except ValueError:
            continue
        if parsed.username is not None or parsed.password is not None:
            return candidate
    return None


# [FIX #2] Proper escape char handling + comment detection
def _in_comment_or_string(line: str, match_start: int, comment_prefix: str = "#") -> bool:
    """Check if match_start position is inside a comment or string literal."""
    stripped = line.lstrip()
    if stripped.startswith(comment_prefix):
        return True
    in_str = False
    str_char = None
    i = 0
    while i < len(line):
        if i >= match_start and not in_str:
            return False
        c = line[i]
        if c == "\\" and in_str:
            i += 2  # skip escaped character
            continue
        if c in ('"', "'") and not in_str:
            in_str = True
            str_char = c
        elif c == str_char and in_str:
            in_str = False
        i += 1
    return in_str


# ---------------------------------------------------------------------------
# Cyclomatic complexity (Python-specific, AST-based)
# ---------------------------------------------------------------------------


class _ComplexityVisitor(ast.NodeVisitor):
    def __init__(self):
        self.complexity = 1

    def visit_If(self, node):
        self.complexity += 1
        self.generic_visit(node)

    def visit_For(self, node):
        self.complexity += 1
        self.generic_visit(node)

    def visit_While(self, node):
        self.complexity += 1
        self.generic_visit(node)

    def visit_ExceptHandler(self, node):
        self.complexity += 1
        self.generic_visit(node)

    def visit_With(self, node):
        self.complexity += 1
        self.generic_visit(node)

    def visit_BoolOp(self, node):
        self.complexity += len(node.values) - 1
        self.generic_visit(node)

    def visit_IfExp(self, node):
        self.complexity += 1
        self.generic_visit(node)

    def visit_comprehension(self, node):
        self.complexity += 1
        self.complexity += len(node.ifs)
        self.generic_visit(node)


def _python_cyclomatic(func_node: ast.AST) -> int:
    v = _ComplexityVisitor()
    v.visit(func_node)
    return v.complexity


# [FIX #5] Helper: find first code line (skip module docstring / comments)
def _first_code_line(source: str) -> int:
    """Return the 1-indexed line number of the first def/class/import statement."""
    for i, line in enumerate(source.split("\n"), 1):
        stripped = line.strip()
        if (
            stripped
            and not stripped.startswith("#")
            and not stripped.startswith('"""')
            and not stripped.startswith("'''")
            and not stripped.startswith('"')
            and not stripped.startswith("'")
        ):
            if any(stripped.startswith(kw) for kw in ("def ", "class ", "import ", "from ", "@")):
                return i
    return 1
