#!/usr/bin/env python3
"""
Deterministic static code analysis tool.

Scans source files for readability, performance, and security issues.
Outputs structured reports (JSON or Markdown) for LLM orchestration.

Usage:
    python code_improver.py <path> [--format json|markdown] [--severity low|medium|high]
                                   [--category readability|performance|security]
                                   [--exclude patterns]
"""

import ast
import argparse
import json
import os
import re
import sys
from urllib.parse import urlsplit
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import List, Optional, Dict, Tuple, Callable


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class Issue:
    file: str
    line: int
    column: int
    category: str  # readability | performance | security
    severity: str  # low | medium | high
    rule_id: str
    message: str
    code_snippet: str
    suggestion_hint: str


@dataclass
class FileMetrics:
    total_lines: int = 0
    code_lines: int = 0
    function_count: int = 0
    max_complexity: int = 0
    avg_function_length: float = 0.0


@dataclass
class FileReport:
    path: str
    language: str
    issues: List[Issue] = field(default_factory=list)
    metrics: Optional[FileMetrics] = None
    skipped: bool = False
    skipped_reason: str = ""


@dataclass
class AnalysisReport:
    files: List[FileReport] = field(default_factory=list)
    summary: Dict = field(default_factory=dict)
    timestamp: str = ""


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

LANGUAGE_MAP = {
    ".py": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".java": "java",
    ".go": "go",
    ".c": "c",
    ".h": "c",
    ".cpp": "cpp",
    ".cc": "cpp",
    ".cxx": "cpp",
    ".hpp": "cpp",
}

SEVERITY_ORDER = {"low": 0, "medium": 1, "high": 2}

DEFAULT_EXCLUDES = {
    "node_modules",
    "__pycache__",
    ".git",
    "venv",
    ".venv",
    "dist",
    "build",
    ".next",
    ".tmp",
    "vendor",
    "target",
    ".agent",
    ".agents",
    ".claude",
    ".codex",
}

# [FIX #7] Bounded quantifiers to prevent ReDoS
SECRET_PATTERNS = [
    re.compile(
        r"(?:password|passwd|pwd|secret|api_?key|token|auth)"
        r"\s{0,5}[=:]\s{0,5}['\"][^'\"]{4,200}['\"]",
        re.IGNORECASE,
    ),
    re.compile(
        r"(?:AWS|AZURE|GCP|GITHUB|SLACK)\w{0,20}"
        r"(?:KEY|SECRET|TOKEN)\s{0,5}[=:]\s{0,5}['\"][^'\"]{1,200}['\"]",
        re.IGNORECASE,
    ),
]

URL_CANDIDATE_PATTERN = re.compile(r"""https?://[^\s"'`<>]+""", re.IGNORECASE)
HASHED_BUNDLE_PATTERN = re.compile(r".*[-.][a-f0-9]{8,}\.(?:js|mjs|cjs|css)$", re.IGNORECASE)

FUNCTION_LENGTH_LIMIT = 180
FUNCTION_COMPLEXITY_LIMIT = 20


# ---------------------------------------------------------------------------
# Utility helpers
# ---------------------------------------------------------------------------


def detect_language(file_path: str) -> Optional[str]:
    ext = Path(file_path).suffix.lower()
    return LANGUAGE_MAP.get(ext)


# [FIX #1] Added OSError handling for permission denied / locked files
def read_file_safe(file_path: str) -> Optional[str]:
    for enc in ("utf-8", "latin-1"):
        try:
            return Path(file_path).read_text(encoding=enc)
        except (UnicodeDecodeError, ValueError):
            continue
        except OSError:
            return None
    return None


def is_binary(file_path: str) -> bool:
    try:
        with open(file_path, "rb") as f:
            chunk = f.read(8192)
        return b"\x00" in chunk
    except OSError:
        return True


def is_minified(source: str) -> bool:
    lines = source.split("\n")
    if len(lines) < 3:
        return any(len(l) > 5000 for l in lines)
    avg_len = sum(len(l) for l in lines) / max(len(lines), 1)
    return avg_len > 500


def is_generated(source: str) -> bool:
    header = source[:1000].lower()
    markers = [
        "generated by",
        "auto-generated",
        "@generated",
        "do not edit",
        "automatically generated",
        "this file is generated",
    ]
    return any(m in header for m in markers)


def is_generated_filename(file_path: str) -> bool:
    name = Path(file_path).name
    if name.lower().startswith("workbox-"):
        return True
    return bool(HASHED_BUNDLE_PATTERN.match(name))


def should_skip(file_path: str, source: str, max_size: int) -> Tuple[bool, str]:
    try:
        size = os.path.getsize(file_path)
    except OSError:
        return True, "Cannot access file"
    if size > max_size:
        return True, f"File too large ({size} bytes > {max_size})"
    if is_binary(file_path):
        return True, "Binary file"
    if not source or not source.strip():
        return True, "Empty file"
    if is_minified(source):
        return True, "Minified file"
    if is_generated(source):
        return True, "Generated file"
    if is_generated_filename(file_path):
        return True, "Generated bundle file"
    return False, ""


def extract_snippet(lines: List[str], line_num: int, context: int = 0) -> str:
    idx = line_num - 1
    start = max(0, idx - context)
    end = min(len(lines), idx + context + 1)
    return "\n".join(lines[start:end]).rstrip()


def _find_embedded_credential_url(line: str) -> Optional[str]:
    """Return a URL with userinfo (username/password) embedded in the authority if found."""
    for match in URL_CANDIDATE_PATTERN.finditer(line):
        candidate = match.group(0).rstrip(".,);]")
        try:
            parsed = urlsplit(candidate)
        except ValueError:
            continue
        if parsed.username is not None or parsed.password is not None:
            return candidate
    return None


# [FIX #2] Proper escape char handling + comment detection
def _in_comment_or_string(line: str, match_start: int, comment_prefix: str = "#") -> bool:
    """Check if match_start position is inside a comment or string literal."""
    stripped = line.lstrip()
    if stripped.startswith(comment_prefix):
        return True
    in_str = False
    str_char = None
    i = 0
    while i < len(line):
        if i >= match_start and not in_str:
            return False
        c = line[i]
        if c == "\\" and in_str:
            i += 2  # skip escaped character
            continue
        if c in ('"', "'") and not in_str:
            in_str = True
            str_char = c
        elif c == str_char and in_str:
            in_str = False
        i += 1
    return in_str


# ---------------------------------------------------------------------------
# Cyclomatic complexity (Python-specific, AST-based)
# ---------------------------------------------------------------------------


class _ComplexityVisitor(ast.NodeVisitor):
    def __init__(self):
        self.complexity = 1

    def visit_If(self, node):
        self.complexity += 1
        self.generic_visit(node)

    def visit_For(self, node):
        self.complexity += 1
        self.generic_visit(node)

    def visit_While(self, node):
        self.complexity += 1
        self.generic_visit(node)

    def visit_ExceptHandler(self, node):
        self.complexity += 1
        self.generic_visit(node)

    def visit_With(self, node):
        self.complexity += 1
        self.generic_visit(node)

    def visit_BoolOp(self, node):
        self.complexity += len(node.values) - 1
        self.generic_visit(node)

    def visit_IfExp(self, node):
        self.complexity += 1
        self.generic_visit(node)

    def visit_comprehension(self, node):
        self.complexity += 1
        self.complexity += len(node.ifs)
        self.generic_visit(node)


def _python_cyclomatic(func_node: ast.AST) -> int:
    v = _ComplexityVisitor()
    v.visit(func_node)
    return v.complexity


# [FIX #5] Helper: find first code line (skip module docstring / comments)
def _first_code_line(source: str) -> int:
    """Return the 1-indexed line number of the first def/class/import statement."""
    for i, line in enumerate(source.split("\n"), 1):
        stripped = line.strip()
        if (
            stripped
            and not stripped.startswith("#")
            and not stripped.startswith('"""')
            and not stripped.startswith("'''")
            and not stripped.startswith('"')
            and not stripped.startswith("'")
        ):
            if any(stripped.startswith(kw) for kw in ("def ", "class ", "import ", "from ", "@")):
                return i
    return 1


# ---------------------------------------------------------------------------
# Base Analyzer (cross-language rules)
# ---------------------------------------------------------------------------


class BaseAnalyzer:
    language = "generic"
    comment_chars = "#"

    def analyze(self, source: str, file_path: str) -> Tuple[List[Issue], FileMetrics]:
        lines = source.split("\n")
        issues = []
        issues.extend(self._check_line_length(lines, file_path))
        issues.extend(self._check_file_length(lines, file_path))
        issues.extend(self._check_todo_fixme(lines, file_path))
        issues.extend(self._check_hardcoded_credentials(lines, file_path))
        metrics = FileMetrics(
            total_lines=len(lines),
            code_lines=sum(1 for l in lines if l.strip() and not l.strip().startswith(self.comment_chars)),
        )
        return issues, metrics

    def _check_line_length(self, lines, fp, limit=120):
        issues = []
        for i, line in enumerate(lines, 1):
            if len(line) > limit:
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=limit,
                        category="readability",
                        severity="low",
                        rule_id="GEN001",
                        message=f"Line is {len(line)} characters (limit {limit}).",
                        code_snippet=line[:140] + "..." if len(line) > 140 else line,
                        suggestion_hint="Break long lines for readability.",
                    )
                )
        return issues

    def _check_file_length(self, lines, fp, limit=500):
        if len(lines) > limit:
            return [
                Issue(
                    file=fp,
                    line=1,
                    column=0,
                    category="readability",
                    severity="low",
                    rule_id="GEN005",
                    message=f"File has {len(lines)} lines (>{limit}). Consider splitting.",
                    code_snippet="",
                    suggestion_hint="Split into smaller modules.",
                )
            ]
        return []

    # [FIX #6] Only match TODO/FIXME in actual comments, not string literals
    def _check_todo_fixme(self, lines, fp):
        issues = []
        if self.comment_chars == "#":
            pattern = re.compile(r"^\s*#\s*(TODO|FIXME|HACK|XXX)\b", re.IGNORECASE)
        else:
            pattern = re.compile(r"^\s*(?://|/\*)\s*(TODO|FIXME|HACK|XXX)\b", re.IGNORECASE)
        for i, line in enumerate(lines, 1):
            m = pattern.search(line)
            if m:
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=m.start(),
                        category="readability",
                        severity="medium",
                        rule_id="GEN003",
                        message=f"Unresolved {m.group(0)} comment found.",
                        code_snippet=line.strip(),
                        suggestion_hint="Resolve or track in issue tracker.",
                    )
                )
        return issues

    def _check_hardcoded_credentials(self, lines, fp):
        issues = []
        for i, line in enumerate(lines, 1):
            secret_detected = False
            for pat in SECRET_PATTERNS:
                if pat.search(line):
                    issues.append(
                        Issue(
                            file=fp,
                            line=i,
                            column=0,
                            category="security",
                            severity="high",
                            rule_id="GEN004",
                            message="Possible hardcoded secret/credential.",
                            code_snippet=line.strip(),
                            suggestion_hint="Use environment variables or a secrets manager.",
                        )
                    )
                    secret_detected = True
                    break
            if secret_detected:
                continue

            credential_url = _find_embedded_credential_url(line)
            if credential_url:
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="security",
                        severity="high",
                        rule_id="GEN004",
                        message="URL contains embedded credentials.",
                        code_snippet=credential_url,
                        suggestion_hint="Remove credentials from URLs; use auth headers.",
                    )
                )
        return issues


# ---------------------------------------------------------------------------
# Python Analyzer (AST-based)
# ---------------------------------------------------------------------------


class PythonAnalyzer(BaseAnalyzer):
    language = "python"
    comment_chars = "#"

    def analyze(self, source: str, file_path: str) -> Tuple[List[Issue], FileMetrics]:
        issues, metrics = super().analyze(source, file_path)
        lines = source.split("\n")

        try:
            tree = ast.parse(source, filename=file_path)
        except SyntaxError:
            return issues, metrics

        issues.extend(self._check_star_imports(tree, file_path))
        issues.extend(self._check_bare_except(tree, file_path))
        issues.extend(self._check_eval_exec(tree, file_path))
        issues.extend(self._check_mutable_defaults(tree, file_path))
        issues.extend(self._check_naming(tree, file_path))
        issues.extend(self._check_function_length(tree, lines, file_path))
        issues.extend(self._check_complexity(tree, file_path))
        issues.extend(self._check_nesting_depth(source, lines, file_path))
        issues.extend(self._check_type_hints(tree, file_path))
        issues.extend(self._check_assert_non_test(tree, file_path))
        issues.extend(self._check_sql_injection(lines, file_path))
        issues.extend(self._check_string_concat_loop(tree, file_path))

        funcs = [n for n in ast.walk(tree) if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))]
        metrics.function_count = len(funcs)
        if funcs:
            lengths = []
            complexities = []
            for f in funcs:
                body_lines = (f.end_lineno or f.lineno) - f.lineno + 1
                lengths.append(body_lines)
                complexities.append(_python_cyclomatic(f))
            metrics.avg_function_length = sum(lengths) / len(lengths)
            metrics.max_complexity = max(complexities) if complexities else 0

        return issues, metrics

    def _check_star_imports(self, tree, fp):
        issues = []
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom):
                for alias in node.names:
                    if alias.name == "*":
                        issues.append(
                            Issue(
                                file=fp,
                                line=node.lineno,
                                column=0,
                                category="readability",
                                severity="low",
                                rule_id="PY001",
                                message=f"Star import from '{node.module}' pollutes namespace.",
                                code_snippet=f"from {node.module} import *",
                                suggestion_hint="Import specific names instead.",
                            )
                        )
        return issues

    def _check_bare_except(self, tree, fp):
        issues = []
        for node in ast.walk(tree):
            if isinstance(node, ast.ExceptHandler) and node.type is None:
                issues.append(
                    Issue(
                        file=fp,
                        line=node.lineno,
                        column=0,
                        category="security",
                        severity="medium",
                        rule_id="PY013",
                        message="Bare 'except:' catches SystemExit and KeyboardInterrupt.",
                        code_snippet="except:",
                        suggestion_hint="Use 'except Exception:' instead.",
                    )
                )
        return issues

    def _check_eval_exec(self, tree, fp):
        issues = []
        for node in ast.walk(tree):
            if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
                if node.func.id in ("eval", "exec"):
                    issues.append(
                        Issue(
                            file=fp,
                            line=node.lineno,
                            column=node.col_offset,
                            category="security",
                            severity="high",
                            rule_id="PY011",
                            message=f"Use of {node.func.id}() allows arbitrary code execution.",
                            code_snippet=f"{node.func.id}(...)",
                            suggestion_hint="Use ast.literal_eval() or a safer alternative.",
                        )
                    )
        return issues

    def _check_mutable_defaults(self, tree, fp):
        issues = []
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                for default in node.args.defaults + node.args.kw_defaults:
                    if default and isinstance(default, (ast.List, ast.Dict, ast.Set)):
                        issues.append(
                            Issue(
                                file=fp,
                                line=node.lineno,
                                column=0,
                                category="performance",
                                severity="medium",
                                rule_id="PY008",
                                message=f"Mutable default argument in '{node.name}()'. Shared across calls.",
                                code_snippet=f"def {node.name}(...)",
                                suggestion_hint="Use None as default; create mutable inside function body.",
                            )
                        )
        return issues

    # [FIX #4] Exempt ast.NodeVisitor visit_* methods and _-prefixed private classes
    def _check_naming(self, tree, fp):
        issues = []
        snake_re = re.compile(r"^[a-z_][a-z0-9_]*$")
        pascal_re = re.compile(r"^_?[A-Z][a-zA-Z0-9]*$")
        visitor_method_re = re.compile(r"^visit_[A-Z]")

        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                name = node.name
                if name.startswith("_"):
                    continue
                if visitor_method_re.match(name):
                    continue
                if name.startswith("test"):
                    continue
                if not snake_re.match(name):
                    issues.append(
                        Issue(
                            file=fp,
                            line=node.lineno,
                            column=0,
                            category="readability",
                            severity="low",
                            rule_id="PY003",
                            message=f"Function '{name}' should be snake_case.",
                            code_snippet=f"def {name}(...):",
                            suggestion_hint="Rename to snake_case.",
                        )
                    )
            elif isinstance(node, ast.ClassDef):
                if not pascal_re.match(node.name):
                    issues.append(
                        Issue(
                            file=fp,
                            line=node.lineno,
                            column=0,
                            category="readability",
                            severity="low",
                            rule_id="PY004",
                            message=f"Class '{node.name}' should be PascalCase.",
                            code_snippet=f"class {node.name}:",
                            suggestion_hint="Rename to PascalCase.",
                        )
                    )
        return issues

    def _is_test_context(self, fp: str, func_name: str) -> bool:
        norm = fp.replace("\\", "/").lower()
        if "/tests/" in norm or Path(fp).name.startswith("test_"):
            return True
        if func_name.startswith("test_"):
            return True
        return False

    def _is_data_heavy_function(self, node: ast.AST) -> bool:
        """Detect functions mostly used for big literal initialization blocks."""
        for child in ast.walk(node):
            if isinstance(child, ast.List) and len(child.elts) >= 150:
                return True
            if isinstance(child, ast.Tuple) and len(child.elts) >= 150:
                return True
            if isinstance(child, ast.Set) and len(child.elts) >= 150:
                return True
            if isinstance(child, ast.Dict) and len(child.keys) >= 100:
                return True
        return False

    def _is_dispatcher_function(self, node: ast.AST) -> bool:
        """Detect large intent-routing/dispatcher functions where branch count is expected."""
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            return False
        length = (node.end_lineno or node.lineno) - node.lineno + 1
        if length < 120:
            return False

        if_count = 0
        return_count = 0
        for child in ast.walk(node):
            if isinstance(child, ast.If):
                if_count += 1
            elif isinstance(child, ast.Return):
                return_count += 1
        return if_count >= 8 and return_count >= 6

    def _check_function_length(self, tree, lines, fp, limit=FUNCTION_LENGTH_LIMIT):
        issues = []
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if self._is_test_context(fp, node.name):
                    continue
                if node.name == "main":
                    continue
                if self._is_data_heavy_function(node):
                    continue
                length = (node.end_lineno or node.lineno) - node.lineno + 1
                if length > limit:
                    issues.append(
                        Issue(
                            file=fp,
                            line=node.lineno,
                            column=0,
                            category="readability",
                            severity="medium",
                            rule_id="PY002",
                            message=f"Function '{node.name}' is {length} lines (>{limit}).",
                            code_snippet=f"def {node.name}(...):",
                            suggestion_hint="Extract helper functions to reduce length.",
                        )
                    )
        return issues

    def _check_complexity(self, tree, fp, limit=FUNCTION_COMPLEXITY_LIMIT):
        issues = []
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if self._is_test_context(fp, node.name):
                    continue
                if node.name == "main":
                    continue
                if self._is_dispatcher_function(node):
                    continue
                cc = _python_cyclomatic(node)
                if cc > limit:
                    issues.append(
                        Issue(
                            file=fp,
                            line=node.lineno,
                            column=0,
                            category="readability",
                            severity="medium",
                            rule_id="PY005",
                            message=f"Function '{node.name}' has cyclomatic complexity {cc} (>{limit}).",
                            code_snippet=f"def {node.name}(...):",
                            suggestion_hint="Simplify logic; extract conditions or use early returns.",
                        )
                    )
        return issues

    # [FIX #5] Skip lines before first code statement (docstrings, etc.)
    def _check_nesting_depth(self, source, lines, fp, limit=4):
        issues = []
        first_code = _first_code_line(source)
        for i, line in enumerate(lines, 1):
            if i < first_code:
                continue
            if not line.strip():
                continue
            indent = len(line) - len(line.lstrip())
            depth = indent // 4
            if depth > limit and not line.strip().startswith("#"):
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="readability",
                        severity="low",
                        rule_id="PY006",
                        message=f"Nesting depth {depth} exceeds {limit}.",
                        code_snippet=line.rstrip(),
                        suggestion_hint="Use early returns or extract nested logic.",
                    )
                )
                break  # Report once per file to avoid noise
        return issues

    # [FIX from review] Simplified type hint check logic
    def _check_type_hints(self, tree, fp):
        issues = []
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if node.name.startswith("_"):
                    continue
                non_self_args = [a for a in node.args.args if a.arg not in ("self", "cls")]
                if not non_self_args:
                    continue
                args_all_missing = all(a.annotation is None for a in non_self_args)
                return_missing = node.returns is None
                if args_all_missing and return_missing:
                    issues.append(
                        Issue(
                            file=fp,
                            line=node.lineno,
                            column=0,
                            category="readability",
                            severity="low",
                            rule_id="PY007",
                            message=f"Function '{node.name}' has no type hints.",
                            code_snippet=f"def {node.name}(...):",
                            suggestion_hint="Add type annotations for parameters and return type.",
                        )
                    )
        return issues

    def _check_assert_non_test(self, tree, fp):
        if "test" in Path(fp).stem.lower():
            return []
        issues = []
        for node in ast.walk(tree):
            if isinstance(node, ast.Assert):
                issues.append(
                    Issue(
                        file=fp,
                        line=node.lineno,
                        column=0,
                        category="security",
                        severity="low",
                        rule_id="PY015",
                        message="assert used for validation (stripped with python -O).",
                        code_snippet="assert ...",
                        suggestion_hint="Use if/raise for validation instead of assert.",
                    )
                )
                break
        return issues

    def _check_sql_injection(self, lines, fp):
        issues = []
        sql_pattern = re.compile(
            r"(?:execute|cursor\.execute)\s*\(\s*f['\"]"
            r"|(?:execute|cursor\.execute)\s*\(\s*['\"].*%s"
            r"|(?:execute|cursor\.execute)\s*\(\s*['\"].*\bformat\(",
            re.IGNORECASE,
        )
        for i, line in enumerate(lines, 1):
            if sql_pattern.search(line):
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="security",
                        severity="high",
                        rule_id="PY014",
                        message="SQL query built with string formatting (injection risk).",
                        code_snippet=line.strip(),
                        suggestion_hint="Use parameterized queries with placeholders.",
                    )
                )
        return issues

    # [FIX #3] Only flag when the augmented value is a string (not integer +=)
    def _check_string_concat_loop(self, tree, fp):
        issues = []
        for node in ast.walk(tree):
            if isinstance(node, (ast.For, ast.While)):
                for child in ast.walk(node):
                    if isinstance(child, ast.AugAssign) and isinstance(child.op, ast.Add):
                        if isinstance(child.target, ast.Name):
                            val = child.value
                            is_string_op = False
                            if isinstance(val, ast.Constant) and isinstance(val.value, str):
                                is_string_op = True
                            elif isinstance(val, ast.JoinedStr):
                                is_string_op = True
                            elif isinstance(val, ast.BinOp) and isinstance(val.op, ast.Add):
                                is_string_op = True
                            elif isinstance(val, ast.Call):
                                # e.g., str(...) or .format(...)
                                is_string_op = True
                            if is_string_op:
                                issues.append(
                                    Issue(
                                        file=fp,
                                        line=child.lineno,
                                        column=0,
                                        category="performance",
                                        severity="low",
                                        rule_id="PY009",
                                        message="String concatenation in loop may be slow.",
                                        code_snippet=f"{child.target.id} += ...",
                                        suggestion_hint="Collect in a list and use ''.join().",
                                    )
                                )
                                break
        return issues


# ---------------------------------------------------------------------------
# JavaScript / TypeScript Analyzer (regex-based)
# ---------------------------------------------------------------------------


class JSAnalyzer(BaseAnalyzer):
    language = "javascript"
    comment_chars = "//"

    def __init__(self, is_typescript: bool = False):
        self.is_typescript = is_typescript

    def analyze(self, source: str, file_path: str) -> Tuple[List[Issue], FileMetrics]:
        issues, metrics = super().analyze(source, file_path)
        lines = source.split("\n")

        issues.extend(self._check_var_usage(lines, file_path))
        issues.extend(self._check_loose_equality(lines, file_path))
        issues.extend(self._check_console_log(lines, file_path))
        issues.extend(self._check_eval(lines, file_path))
        issues.extend(self._check_innerhtml(lines, file_path))
        issues.extend(self._check_callback_nesting(lines, file_path))
        issues.extend(self._check_document_write(lines, file_path))
        issues.extend(self._check_sql_injection(lines, file_path))

        if self.is_typescript:
            issues.extend(self._check_any_type(lines, file_path))
            issues.extend(self._check_ts_ignore(lines, file_path))

        func_pattern = re.compile(r"\bfunction\b|=>")
        metrics.function_count = sum(1 for l in lines if func_pattern.search(l))

        return issues, metrics

    # [FIX #2] All callers now pass actual match position to _in_comment_or_string
    def _check_var_usage(self, lines, fp):
        issues = []
        pat = re.compile(r"\bvar\s+\w+")
        for i, line in enumerate(lines, 1):
            m = pat.search(line)
            if m and not _in_comment_or_string(line, m.start(), "//"):
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="readability",
                        severity="medium",
                        rule_id="JS001",
                        message="'var' is function-scoped. Use 'let' or 'const'.",
                        code_snippet=line.strip(),
                        suggestion_hint="Replace var with let or const.",
                    )
                )
        return issues

    def _check_loose_equality(self, lines, fp):
        issues = []
        pat = re.compile(r"[^=!]==[^=]|[^!]!=[^=]")
        for i, line in enumerate(lines, 1):
            m = pat.search(line)
            if m and not _in_comment_or_string(line, m.start(), "//"):
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="performance",
                        severity="low",
                        rule_id="JS005",
                        message="Loose equality (==). Use strict equality (===).",
                        code_snippet=line.strip(),
                        suggestion_hint="Replace == with === and != with !==.",
                    )
                )
        return issues

    def _check_console_log(self, lines, fp):
        issues = []
        pat = re.compile(r"\bconsole\.\w+\(")
        for i, line in enumerate(lines, 1):
            m = pat.search(line)
            if m and not _in_comment_or_string(line, m.start(), "//"):
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="readability",
                        severity="low",
                        rule_id="JS002",
                        message="console.log left in code.",
                        code_snippet=line.strip(),
                        suggestion_hint="Remove or replace with a proper logger.",
                    )
                )
        return issues

    def _check_eval(self, lines, fp):
        issues = []
        pat = re.compile(r"\beval\s*\(")
        for i, line in enumerate(lines, 1):
            m = pat.search(line)
            if m and not _in_comment_or_string(line, m.start(), "//"):
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="security",
                        severity="high",
                        rule_id="JS006",
                        message="eval() allows arbitrary code execution.",
                        code_snippet=line.strip(),
                        suggestion_hint="Use JSON.parse() or a safer alternative.",
                    )
                )
        return issues

    def _check_innerhtml(self, lines, fp):
        issues = []
        pat = re.compile(r"\.innerHTML\s*=")
        for i, line in enumerate(lines, 1):
            if pat.search(line):
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="security",
                        severity="high",
                        rule_id="JS007",
                        message="innerHTML assignment is an XSS risk.",
                        code_snippet=line.strip(),
                        suggestion_hint="Use textContent or a sanitization library.",
                    )
                )
        return issues

    # [FIX #10] Skip comment lines; use function( pattern not bare keyword
    def _check_callback_nesting(self, lines, fp, limit=3):
        issues = []
        depth = 0
        max_depth = 0
        max_line = 0
        func_open = re.compile(r"\bfunction\s*\(|=>\s*\{")
        for i, line in enumerate(lines, 1):
            stripped = line.strip()
            if stripped.startswith("//") or stripped.startswith("/*") or stripped.startswith("*"):
                continue
            opens = len(func_open.findall(line))
            closes = line.count("}")
            depth += opens
            if depth > max_depth:
                max_depth = depth
                max_line = i
            depth = max(0, depth - closes)
        if max_depth > limit:
            issues.append(
                Issue(
                    file=fp,
                    line=max_line,
                    column=0,
                    category="readability",
                    severity="medium",
                    rule_id="JS003",
                    message=f"Callback nesting depth {max_depth} (>{limit}).",
                    code_snippet=lines[max_line - 1].strip() if max_line <= len(lines) else "",
                    suggestion_hint="Use async/await or extract named functions.",
                )
            )
        return issues

    def _check_document_write(self, lines, fp):
        issues = []
        pat = re.compile(r"\bdocument\.write\s*\(")
        for i, line in enumerate(lines, 1):
            if pat.search(line):
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="security",
                        severity="medium",
                        rule_id="JS009",
                        message="document.write() blocks parsing and is an XSS risk.",
                        code_snippet=line.strip(),
                        suggestion_hint="Use DOM manipulation methods instead.",
                    )
                )
        return issues

    def _check_sql_injection(self, lines, fp):
        issues = []
        pat = re.compile(r"""(?:query|execute)\s*\(\s*[`'"].*\$\{""")
        for i, line in enumerate(lines, 1):
            if pat.search(line):
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="security",
                        severity="medium",
                        rule_id="JS008",
                        message="SQL query built with template literals (injection risk).",
                        code_snippet=line.strip(),
                        suggestion_hint="Use parameterized queries.",
                    )
                )
        return issues

    def _check_any_type(self, lines, fp):
        issues = []
        pat = re.compile(r":\s*any\b")
        for i, line in enumerate(lines, 1):
            m = pat.search(line)
            if m and not _in_comment_or_string(line, m.start(), "//"):
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="readability",
                        severity="medium",
                        rule_id="TS001",
                        message="'any' type defeats TypeScript's type safety.",
                        code_snippet=line.strip(),
                        suggestion_hint="Use a specific type or 'unknown'.",
                    )
                )
        return issues

    def _check_ts_ignore(self, lines, fp):
        issues = []
        for i, line in enumerate(lines, 1):
            if "@ts-ignore" in line or "@ts-nocheck" in line:
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="readability",
                        severity="low",
                        rule_id="TS002",
                        message="@ts-ignore suppresses type checking.",
                        code_snippet=line.strip(),
                        suggestion_hint="Fix the type error instead of suppressing.",
                    )
                )
        return issues


# ---------------------------------------------------------------------------
# Java Analyzer (regex-based)
# ---------------------------------------------------------------------------


class JavaAnalyzer(BaseAnalyzer):
    language = "java"
    comment_chars = "//"

    def analyze(self, source: str, file_path: str) -> Tuple[List[Issue], FileMetrics]:
        issues, metrics = super().analyze(source, file_path)
        lines = source.split("\n")

        issues.extend(self._check_empty_catch(source, lines, file_path))
        issues.extend(self._check_string_concat_loop(lines, file_path))
        issues.extend(self._check_raw_types(lines, file_path))
        issues.extend(self._check_system_exit(lines, file_path))
        issues.extend(self._check_sql_injection(lines, file_path))
        issues.extend(self._check_sysout(lines, file_path))

        metrics.function_count = len(re.findall(r"\b(?:public|private|protected)\s+\w+\s+\w+\s*\(", source))
        return issues, metrics

    def _check_empty_catch(self, source, lines, fp):
        issues = []
        pat = re.compile(r"catch\s*\([^)]*\)\s*\{\s*\}", re.DOTALL)
        for m in pat.finditer(source):
            line_num = source[: m.start()].count("\n") + 1
            issues.append(
                Issue(
                    file=fp,
                    line=line_num,
                    column=0,
                    category="readability",
                    severity="medium",
                    rule_id="JV001",
                    message="Empty catch block swallows exception.",
                    code_snippet=m.group(0).strip(),
                    suggestion_hint="Log the exception or handle it properly.",
                )
            )
        return issues

    # [FIX #11] Use brace depth counter instead of boolean for nested blocks
    def _check_string_concat_loop(self, lines, fp):
        issues = []
        loop_pat = re.compile(r"\b(for|while)\s*\(")
        concat_pat = re.compile(r'\+\s*=\s*"|\+\s*=\s*\w+')
        brace_depth = 0
        in_loop = False
        for i, line in enumerate(lines, 1):
            if loop_pat.search(line):
                in_loop = True
                brace_depth = line.count("{") - line.count("}")
            elif in_loop:
                brace_depth += line.count("{") - line.count("}")
                if brace_depth <= 0:
                    in_loop = False
                    brace_depth = 0
                    continue
                if concat_pat.search(line):
                    issues.append(
                        Issue(
                            file=fp,
                            line=i,
                            column=0,
                            category="performance",
                            severity="medium",
                            rule_id="JV003",
                            message="String concatenation in loop. Use StringBuilder.",
                            code_snippet=line.strip(),
                            suggestion_hint="Replace with StringBuilder.append().",
                        )
                    )
        return issues

    def _check_raw_types(self, lines, fp):
        issues = []
        pat = re.compile(r"\b(List|Map|Set|Collection|ArrayList|HashMap|HashSet)\s+\w+\s*[=;]")
        for i, line in enumerate(lines, 1):
            if pat.search(line) and "<" not in line:
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="readability",
                        severity="low",
                        rule_id="JV004",
                        message="Raw generic type. Use parameterized types.",
                        code_snippet=line.strip(),
                        suggestion_hint="Add type parameter e.g., List<String>.",
                    )
                )
        return issues

    def _check_system_exit(self, lines, fp):
        issues = []
        pat = re.compile(r"System\.exit\s*\(")
        for i, line in enumerate(lines, 1):
            if pat.search(line):
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="security",
                        severity="medium",
                        rule_id="JV007",
                        message="System.exit() terminates the JVM abruptly.",
                        code_snippet=line.strip(),
                        suggestion_hint="Throw an exception or use proper shutdown hooks.",
                    )
                )
        return issues

    def _check_sql_injection(self, lines, fp):
        issues = []
        pat = re.compile(r"""(?:executeQuery|executeUpdate|prepareStatement)\s*\(\s*["'].*\+""")
        for i, line in enumerate(lines, 1):
            if pat.search(line):
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="security",
                        severity="high",
                        rule_id="JV006",
                        message="SQL query built with string concatenation.",
                        code_snippet=line.strip(),
                        suggestion_hint="Use PreparedStatement with parameterized queries.",
                    )
                )
        return issues

    def _check_sysout(self, lines, fp):
        issues = []
        pat = re.compile(r"System\.out\.print")
        for i, line in enumerate(lines, 1):
            if pat.search(line):
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="readability",
                        severity="low",
                        rule_id="JV008",
                        message="System.out.println used (use a logger instead).",
                        code_snippet=line.strip(),
                        suggestion_hint="Use SLF4J/Log4j logger.",
                    )
                )
        return issues


# ---------------------------------------------------------------------------
# Go Analyzer (regex-based)
# ---------------------------------------------------------------------------


class GoAnalyzer(BaseAnalyzer):
    language = "go"
    comment_chars = "//"

    def analyze(self, source: str, file_path: str) -> Tuple[List[Issue], FileMetrics]:
        issues, metrics = super().analyze(source, file_path)
        lines = source.split("\n")

        issues.extend(self._check_error_ignored(lines, file_path))
        issues.extend(self._check_panic(lines, file_path))
        issues.extend(self._check_defer_in_loop(lines, file_path))
        issues.extend(self._check_sql_injection(lines, file_path))

        metrics.function_count = len(re.findall(r"\bfunc\s+", source))
        return issues, metrics

    # [FIX #8] Removed unused `pat` variable, added _ discard detection
    def _check_error_ignored(self, lines, fp):
        issues = []
        err_assign = re.compile(r"\w+\s*,\s*err\s*:?=")
        err_discard = re.compile(r"\w+\s*,\s*_\s*:?=")
        err_check = re.compile(r"if\s+err\s*!=\s*nil")
        for i, line in enumerate(lines, 1):
            # Check for explicitly discarded errors: result, _ := ...
            if err_discard.search(line) and not _in_comment_or_string(line, 0, "//"):
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="readability",
                        severity="high",
                        rule_id="GO001",
                        message="Error return value explicitly discarded with '_'.",
                        code_snippet=line.strip(),
                        suggestion_hint="Check error with 'if err != nil { ... }'.",
                    )
                )
                continue
            # Check for err assigned but not checked
            if err_assign.search(line):
                checked = False
                for j in range(i, min(i + 8, len(lines))):
                    if err_check.search(lines[j]):
                        checked = True
                        break
                if not checked:
                    issues.append(
                        Issue(
                            file=fp,
                            line=i,
                            column=0,
                            category="readability",
                            severity="high",
                            rule_id="GO001",
                            message="Error return value not checked.",
                            code_snippet=line.strip(),
                            suggestion_hint="Check error with 'if err != nil { ... }'.",
                        )
                    )
        return issues

    def _check_panic(self, lines, fp):
        issues = []
        pat = re.compile(r"\bpanic\s*\(")
        for i, line in enumerate(lines, 1):
            m = pat.search(line)
            if m and not _in_comment_or_string(line, m.start(), "//"):
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="readability",
                        severity="low",
                        rule_id="GO006",
                        message="panic() used. Prefer error returns in library code.",
                        code_snippet=line.strip(),
                        suggestion_hint="Return an error instead of panicking.",
                    )
                )
        return issues

    # [FIX #11] Use brace depth counter for nested blocks
    def _check_defer_in_loop(self, lines, fp):
        issues = []
        in_loop = False
        brace_depth = 0
        for i, line in enumerate(lines, 1):
            stripped = line.strip()
            if re.match(r"\bfor\b", stripped):
                in_loop = True
                brace_depth = stripped.count("{") - stripped.count("}")
            elif in_loop:
                brace_depth += stripped.count("{") - stripped.count("}")
                if brace_depth <= 0:
                    in_loop = False
                    brace_depth = 0
                    continue
                if "defer " in stripped:
                    issues.append(
                        Issue(
                            file=fp,
                            line=i,
                            column=0,
                            category="performance",
                            severity="low",
                            rule_id="GO005",
                            message="defer inside loop accumulates deferred calls.",
                            code_snippet=stripped,
                            suggestion_hint="Move defer outside loop or use explicit close.",
                        )
                    )
        return issues

    def _check_sql_injection(self, lines, fp):
        issues = []
        pat = re.compile(r"""(?:Query|Exec)\s*\(\s*(?:fmt\.Sprintf|"[^"]*"\s*\+)""")
        for i, line in enumerate(lines, 1):
            if pat.search(line):
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="security",
                        severity="medium",
                        rule_id="GO004",
                        message="SQL query built with string formatting.",
                        code_snippet=line.strip(),
                        suggestion_hint="Use parameterized queries with $1, $2 placeholders.",
                    )
                )
        return issues


# ---------------------------------------------------------------------------
# C/C++ Analyzer (regex-based)
# ---------------------------------------------------------------------------


class CAnalyzer(BaseAnalyzer):
    language = "c"
    comment_chars = "//"

    def analyze(self, source: str, file_path: str) -> Tuple[List[Issue], FileMetrics]:
        issues, metrics = super().analyze(source, file_path)
        lines = source.split("\n")

        issues.extend(self._check_unsafe_functions(lines, file_path))
        issues.extend(self._check_format_string(lines, file_path))
        issues.extend(self._check_system_call(lines, file_path))

        metrics.function_count = len(re.findall(r"\w+\s+\w+\s*\([^)]*\)\s*\{", source))
        return issues, metrics

    def _check_unsafe_functions(self, lines, fp):
        issues = []
        unsafe = {
            "gets": ("CC001", "gets() has no bounds checking (buffer overflow)."),
            "strcpy": ("CC002", "strcpy() has no bounds checking."),
            "strcat": ("CC002", "strcat() has no bounds checking."),
            "sprintf": ("CC003", "sprintf() has no bounds checking."),
        }
        safe_alt = {"gets": "fgets", "strcpy": "strncpy", "strcat": "strncat", "sprintf": "snprintf"}
        for i, line in enumerate(lines, 1):
            for func, (rule, msg) in unsafe.items():
                pat = re.compile(rf"\b{func}\s*\(")
                m = pat.search(line)
                if m and not _in_comment_or_string(line, m.start(), "//"):
                    issues.append(
                        Issue(
                            file=fp,
                            line=i,
                            column=0,
                            category="security",
                            severity="high",
                            rule_id=rule,
                            message=msg,
                            code_snippet=line.strip(),
                            suggestion_hint=f"Use {safe_alt[func]}() with explicit size.",
                        )
                    )
        return issues

    def _check_format_string(self, lines, fp):
        issues = []
        pat = re.compile(r"\bprintf\s*\(\s*\w+\s*\)")
        for i, line in enumerate(lines, 1):
            if pat.search(line):
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="security",
                        severity="medium",
                        rule_id="CC004",
                        message="printf() called with variable as format string.",
                        code_snippet=line.strip(),
                        suggestion_hint='Use printf("%s", var) to prevent format string attacks.',
                    )
                )
        return issues

    def _check_system_call(self, lines, fp):
        issues = []
        pat = re.compile(r"\bsystem\s*\(")
        for i, line in enumerate(lines, 1):
            m = pat.search(line)
            if m and not _in_comment_or_string(line, m.start(), "//"):
                issues.append(
                    Issue(
                        file=fp,
                        line=i,
                        column=0,
                        category="security",
                        severity="high",
                        rule_id="CC008",
                        message="system() call allows command injection.",
                        code_snippet=line.strip(),
                        suggestion_hint="Use exec family (execvp) with argument arrays.",
                    )
                )
        return issues


# ---------------------------------------------------------------------------
# Report Generator
# ---------------------------------------------------------------------------


class ReportGenerator:
    @staticmethod
    def to_json(report: AnalysisReport) -> str:
        data = {
            "timestamp": report.timestamp,
            "summary": report.summary,
            "files": [],
        }
        for fr in report.files:
            file_data = {
                "path": fr.path,
                "language": fr.language,
                "skipped": fr.skipped,
                "skipped_reason": fr.skipped_reason,
                "metrics": asdict(fr.metrics) if fr.metrics else None,
                "issues": [asdict(i) for i in fr.issues],
            }
            data["files"].append(file_data)
        return json.dumps(data, indent=2, ensure_ascii=False)

    @staticmethod
    def to_markdown(report: AnalysisReport) -> str:
        lines = []
        lines.append("# Code Analysis Report")
        lines.append(f"\n**Timestamp:** {report.timestamp}")
        s = report.summary
        lines.append(
            f"\n**Files analyzed:** {s.get('files_analyzed', 0)} | "
            f"**Skipped:** {s.get('files_skipped', 0)} | "
            f"**Total issues:** {s.get('total_issues', 0)}"
        )

        by_sev = s.get("by_severity", {})
        lines.append("\n| Severity | Count |\n|----------|-------|")
        for sev in ("high", "medium", "low"):
            lines.append(f"| {sev} | {by_sev.get(sev, 0)} |")

        by_cat = s.get("by_category", {})
        lines.append("\n| Category | Count |\n|----------|-------|")
        for cat in ("security", "performance", "readability"):
            lines.append(f"| {cat} | {by_cat.get(cat, 0)} |")

        for fr in report.files:
            lines.append(f"\n---\n## {fr.path} ({fr.language})")
            if fr.skipped:
                lines.append(f"*Skipped: {fr.skipped_reason}*")
                continue
            if fr.metrics:
                m = fr.metrics
                lines.append(
                    f"Lines: {m.total_lines} | Functions: {m.function_count} | Max complexity: {m.max_complexity}"
                )
            if not fr.issues:
                lines.append("*No issues found.*")
                continue
            for issue in fr.issues:
                severity_icon = {"high": "[HIGH]", "medium": "[MED]", "low": "[LOW]"}.get(issue.severity, "")
                lines.append(f"\n### {severity_icon} {issue.rule_id}: {issue.message}")
                lines.append(f"**Category:** {issue.category} | **Line:** {issue.line}")
                if issue.code_snippet:
                    lines.append(f"```\n{issue.code_snippet}\n```")
                lines.append(f"**Suggestion:** {issue.suggestion_hint}")

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main Orchestrator
# ---------------------------------------------------------------------------

ANALYZERS: Dict[str, Callable[[], BaseAnalyzer]] = {
    "python": PythonAnalyzer,
    "javascript": lambda: JSAnalyzer(is_typescript=False),
    "typescript": lambda: JSAnalyzer(is_typescript=True),
    "java": JavaAnalyzer,
    "go": GoAnalyzer,
    "c": CAnalyzer,
    "cpp": CAnalyzer,
}


class CodeImprover:
    def __init__(
        self,
        severity_filter: Optional[str] = None,
        category_filter: Optional[str] = None,
        max_file_size: int = 1_048_576,
        exclude_patterns: Optional[set] = None,
    ):
        self.severity_filter = severity_filter
        self.category_filter = category_filter
        self.max_file_size = max_file_size
        self.exclude_patterns = exclude_patterns or DEFAULT_EXCLUDES

    def _get_analyzer(self, language: str) -> BaseAnalyzer:
        factory = ANALYZERS.get(language)
        if factory is None:
            return BaseAnalyzer()
        return factory()

    def analyze_file(self, file_path: str) -> FileReport:
        fp = str(Path(file_path))
        language = detect_language(fp) or "unknown"

        report = FileReport(path=fp, language=language)

        source = read_file_safe(fp)
        if source is None:
            report.skipped = True
            report.skipped_reason = "Could not read file (encoding or permission error)"
            return report

        skip, reason = should_skip(fp, source, self.max_file_size)
        if skip:
            report.skipped = True
            report.skipped_reason = reason
            return report

        if language == "unknown":
            analyzer = BaseAnalyzer()
        else:
            analyzer = self._get_analyzer(language)

        issues, metrics = analyzer.analyze(source, fp)

        if self.severity_filter:
            min_sev = SEVERITY_ORDER.get(self.severity_filter, 0)
            issues = [i for i in issues if SEVERITY_ORDER.get(i.severity, 0) >= min_sev]

        if self.category_filter:
            issues = [i for i in issues if i.category == self.category_filter]

        report.issues = issues
        report.metrics = metrics
        return report

    def analyze_directory(self, dir_path: str) -> AnalysisReport:
        report = AnalysisReport(timestamp=datetime.now().isoformat())
        dir_p = Path(dir_path)

        for root, dirs, files in os.walk(dir_p):
            dirs[:] = [d for d in dirs if d not in self.exclude_patterns]

            for fname in sorted(files):
                fpath = os.path.join(root, fname)
                # [FIX from review] Simplified dead code double-None check
                if detect_language(fpath) is None:
                    continue

                file_report = self.analyze_file(fpath)
                report.files.append(file_report)

        report.summary = self._compute_summary(report)
        return report

    # [FIX #9] Raise ValueError instead of sys.exit() in library method
    def analyze_path(self, path: str) -> AnalysisReport:
        p = Path(path)
        if p.is_file():
            report = AnalysisReport(timestamp=datetime.now().isoformat())
            file_report = self.analyze_file(path)
            report.files.append(file_report)
            report.summary = self._compute_summary(report)
            return report
        elif p.is_dir():
            return self.analyze_directory(path)
        else:
            raise ValueError(f"'{path}' is not a valid file or directory.")

    @staticmethod
    def _compute_summary(report: AnalysisReport) -> Dict:
        total = 0
        by_sev = {"high": 0, "medium": 0, "low": 0}
        by_cat = {"readability": 0, "performance": 0, "security": 0}
        analyzed = 0
        skipped = 0

        for fr in report.files:
            if fr.skipped:
                skipped += 1
                continue
            analyzed += 1
            for issue in fr.issues:
                total += 1
                by_sev[issue.severity] = by_sev.get(issue.severity, 0) + 1
                by_cat[issue.category] = by_cat.get(issue.category, 0) + 1

        return {
            "files_analyzed": analyzed,
            "files_skipped": skipped,
            "total_issues": total,
            "by_severity": by_sev,
            "by_category": by_cat,
        }


# ---------------------------------------------------------------------------
# CLI Entry Point
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description="Deterministic static code analysis tool.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("path", help="File or directory to analyze")
    parser.add_argument("--format", choices=["json", "markdown"], default="json", help="Output format (default: json)")
    parser.add_argument(
        "--severity", choices=["low", "medium", "high"], default=None, help="Minimum severity to report (default: all)"
    )
    parser.add_argument(
        "--category",
        choices=["readability", "performance", "security"],
        default=None,
        help="Filter by category (default: all)",
    )
    parser.add_argument("--max-file-size", type=int, default=1_048_576, help="Max file size in bytes (default: 1MB)")
    parser.add_argument("--exclude", type=str, default=None, help="Comma-separated directory names to exclude")

    args = parser.parse_args()

    exclude = DEFAULT_EXCLUDES.copy()
    if args.exclude:
        exclude.update(p.strip() for p in args.exclude.split(","))

    improver = CodeImprover(
        severity_filter=args.severity,
        category_filter=args.category,
        max_file_size=args.max_file_size,
        exclude_patterns=exclude,
    )

    try:
        report = improver.analyze_path(args.path)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    if not report.files:
        print("No analyzable files found.", file=sys.stderr)
        sys.exit(2)

    if args.format == "json":
        print(ReportGenerator.to_json(report))
    else:
        print(ReportGenerator.to_markdown(report))

    sys.exit(0)


if __name__ == "__main__":
    main()
