const pptxgen = require("pptxgenjs");

let pres = new pptxgen();
pres.layout = 'LAYOUT_16x9';
pres.author = 'Antigravity Agent';
pres.title = 'Suika Game Match-3 v2.0 Overview';

// Define Colors
const COLORS = {
    primary: "FF6B6B",
    secondary: "4ECDC4",
    accent: "FFE66D",
    dark: "2D3436",
    light: "F7FFF7"
};

// 1. Title Slide
let slide1 = pres.addSlide();
slide1.background = { color: COLORS.light };
slide1.addText("Suika Match-3", {
    x: 0.5, y: 1.5, w: 9, h: 1.5,
    fontSize: 54, color: COLORS.primary, bold: true, align: 'center', fontFace: "Arial Rounded MT Bold"
});
slide1.addText("v2.0 Project Overview", {
    x: 0.5, y: 3.0, w: 9, h: 0.5,
    fontSize: 24, color: COLORS.dark, align: 'center', fontFace: "Arial"
});
slide1.addText("Generated by Antigravity Agent", {
    x: 0.5, y: 4.5, w: 9, h: 0.5,
    fontSize: 14, color: "888888", align: 'center'
});

// 2. Project Goals & Mechanics
let slide2 = pres.addSlide();
slide2.background = { color: "FFFFFF" };
slide2.addShape(pres.shapes.RECTANGLE, { x: 0, y: 0, w: 10, h: 1.2, fill: { color: COLORS.secondary } });
slide2.addText("Game Mechanics", { x: 0.5, y: 0.2, w: 9, h: 0.8, fontSize: 32, color: "FFFFFF", bold: true });

slide2.addText("Core Gameplay (Match-3)", { x: 0.5, y: 1.5, w: 4, h: 0.5, fontSize: 20, bold: true, color: COLORS.dark });
slide2.addText([
    { text: "Physics-based fruit dropping", options: { breakLine: true } },
    { text: "Match-3 Merge Logic (BFS Algorithm)", options: { breakLine: true } },
    { text: "Dynamic evolution: Cherry -> Strawberry -> ... -> Watermelon", options: { breakLine: true } }
], { x: 0.5, y: 2.1, w: 4.5, h: 3, fontSize: 16, color: "555555", bullet: true });

slide2.addText("Tech Stack", { x: 5.5, y: 1.5, w: 4, h: 0.5, fontSize: 20, bold: true, color: COLORS.dark });
slide2.addText([
    { text: "Engine: Matter.js (2D Physics)", options: { breakLine: true } },
    { text: "Rendering: HTML5 Canvas", options: { breakLine: true } },
    { text: "Structure: Single HTML File (Zero-build)", options: { breakLine: true } }
], { x: 5.5, y: 2.1, w: 4, h: 3, fontSize: 16, color: "555555", bullet: true });

// 3. v2.0 Updates (Design)
let slide3 = pres.addSlide();
slide3.background = { color: "FFFFFF" };
slide3.addShape(pres.shapes.RECTANGLE, { x: 0, y: 0, w: 10, h: 1.2, fill: { color: COLORS.primary } });
slide3.addText("v2.0 Design Updates", { x: 0.5, y: 0.2, w: 9, h: 0.8, fontSize: 32, color: "FFFFFF", bold: true });

slide3.addText("UI Enhancements", { x: 0.5, y: 1.5, w: 9, h: 0.5, fontSize: 24, bold: true, color: COLORS.dark });
slide3.addText([
    { text: "Glassmorphism: Translucent UI panels", options: { breakLine: true } },
    { text: "Start Screen: Dedicated landing overlay", options: { breakLine: true } },
    { text: "Typography: Google Fonts (Fredoka, Nunito)", options: { breakLine: true } },
    { text: "Code Quality: JSDoc & Strict Null Checks", options: { breakLine: true } }
], { x: 0.5, y: 2.2, w: 9, h: 3, fontSize: 18, color: "555555", bullet: true });


// 4. Monetization & Future
let slide4 = pres.addSlide();
slide4.background = { color: "FFFFFF" };
slide4.addShape(pres.shapes.RECTANGLE, { x: 0, y: 0, w: 10, h: 1.2, fill: { color: COLORS.dark } });
slide4.addText("Monetization & Roadmap", { x: 0.5, y: 0.2, w: 9, h: 0.8, fontSize: 32, color: "FFFFFF", bold: true });

slide4.addText("Current Features", { x: 0.5, y: 1.5, w: 4, h: 0.5, fontSize: 20, bold: true, color: COLORS.primary });
slide4.addText([
    { text: "Banner Ad Placeholder (320x50)", options: { breakLine: true } },
    { text: "Interstitial Ad Simulation (Retry)", options: { breakLine: true } },
    { text: "Social Sharing (Web Share API)", options: { breakLine: true } }
], { x: 0.5, y: 2.1, w: 4.5, h: 2, fontSize: 16, color: "555555", bullet: true });

slide4.addText("Next Steps", { x: 5.5, y: 1.5, w: 4, h: 0.5, fontSize: 20, bold: true, color: COLORS.secondary });
slide4.addText([
    { text: "Integrate Real Ad Networks (AdMob/AdSense)", options: { breakLine: true } },
    { text: "Add Cloud Leaderboard", options: { breakLine: true } },
    { text: "PWA Support", options: { breakLine: true } }
], { x: 5.5, y: 2.1, w: 4, h: 2, fontSize: 16, color: "555555", bullet: true });

pres.writeFile({ fileName: "Suika_Game_v2_Overview.pptx" });
console.log("PPT Generation Complete");
