import asyncio

import edge_tts


async def main():
    text = "안녕하세요. <prosody rate='+20%' pitch='+10Hz'>이 부분은 빠르고 높게 말합니다.</prosody> 다시 정상입니다."
    import sys

    sys.path.insert(0, r"c:\Users\박주호\Desktop\Vibe coding\shorts-maker-v2\src")
    comm = edge_tts.Communicate(text, "ko-KR-SunHiNeural")

    # We can inspect the SSML generated by edge-tts by looking at the _create_ssml method
    ssml = comm._create_ssml()
    print("Generated SSML:")
    print(ssml)


asyncio.run(main())
